import type { Person } from "@/content/types";

/**
 * This text is shown below the banner image and before the people working at the chair.
 */
export const Introduction: string = "Since 2020, I lead the Chair of Machine Learning at the Institute of Computer Science at the\n" +
                                    "Humboldt University Berlin.\n" +
                                    "Below is a list of my current PhD students and research assistants, plus our alumni.";

export const People: Person[] = [
    {
        name: "Alan Akbik",
        title: "Professor of Machine Learning",
        image: "/people/alan-2024-sq-2.png",
        category: "Head of Lab",
        gitHubLink: "https://github.com/alanakbik",
        googleScholarLink: "https://scholar.google.com/citations?user=adKmg3IAAAAJ&hl=de",
        emailAddress: "alan.akbik@hu-berlin.de",
        linkedInLink: "https://de.linkedin.com/in/alan-akbik-9859b1122",
    }, {
        name: "Ansar Aynetdinov",
        title: "PhD Student",
        image: "/people/ansar.jpg",
        category: "Research Scientists",
        gitHubLink: "https://github.com/aynetdia",
        googleScholarLink: "https://scholar.google.com/citations?user=EqlZ0aAAAAAJ",
        emailAddress: "aynetdia@hu-berlin.de",
        linkedInLink: "https://www.linkedin.com/in/ansar-aynetdinov/",
    }, {
        name: "Max Dallabetta",
        title: "Research Engineer",
        image: "/people/maxd.jpg",
        category: "Research Scientists",
        gitHubLink: "https://github.com/MaxDall",
        linkedInLink: "https://www.linkedin.com/in/max-dallabetta-5905651b4/",
    }, {
        name: "Benedikt Fuchs",
        title: "Research Engineer",
        category: "Research Scientists",
        image: "/people/benedikt.jpg",
        gitHubLink: "https://github.com/helpmefindaname",
        linkedInLink: "https://www.linkedin.com/in/benedikt-fuchs-020a1b100/",
        emailAddress: "benedikt.fuchs.staw@hotmail.com",
    }, {
        name: "Jonas Golde",
        title: "PhD Student",
        image: "/people/jonas.jpg",
        category: "Research Scientists",
        gitHubLink: "https://github.com/whoisjones",
        googleScholarLink: "https://scholar.google.de/citations?user=QVG2t4gAAAAJ",
        emailAddress: "jonas.golde@gmail.com",
        linkedInLink: "https://www.linkedin.com/in/jonasgolde/",
    }, {
        name: "Felix Hamborg",
        title: "Guest Researcher",
        category: "Research Scientists",
        image: "/people/felix.jpg",
        gitHubLink: "https://github.com/fhamborg",
    }, {
        name: "Patrick Haller",
        title: "PhD Student",
        image: "/people/patrick.jpg",
        category: "Research Scientists",
        gitHubLink: "https://github.com/HallerPatrick",
        googleScholarLink: "https://scholar.google.com/citations?user=ZFe7wn4AAAAJ&hl=en",
        linkedInLink: "https://linkedin.com/in/patrick-haller-651493126",
    }, {
        name: "Filipe Laitenberger",
        title: "PhD Student",
        image: "/people/filipe.jpg",
        category: "Research Scientists",
        gitHubLink: "https://github.com/Thiggel",
        googleScholarLink: "https://scholar.google.at/citations?hl=de&user=fVuktiEAAAAJ",
        linkedInLink: "https://www.linkedin.com/in/filipe-laitenberger-17b089191",
    }, {
        name: "Elena Merdjanovska",
        title: "PhD Student",
        category: "Research Scientists",
        gitHubLink: "https://github.com/elenamer",
        googleScholarLink: "https://scholar.google.com/citations?user=6QT6SBQAAAAJ&hl=en",
        emailAddress: "elena.merdjanovska@hu-berlin.de",
        linkedInLink: "https://www.linkedin.com/in/elena-merdjanovska/",
        image: "/people/elena.jpg",
    }, {
        name: "Max Ploner",
        title: "PhD Student",
        category: "Research Scientists",
        image: "/people/max.jpg",
        gitHubLink: "https://github.com/plonerma",
        googleScholarLink: "https://scholar.google.com/citations?user=xdo2T6wAAAAJ&hl=de&oi=ao",
        linkedInLink: "https://www.linkedin.com/in/plonerma/",
        emailAddress: "max.ploner@hu-berlin.de",
    }, {
        name: "Susanna Rücker",
        title: "PhD Student",
        image: "/people/susanna.jpg",
        category: "Research Scientists",
        gitHubLink: "https://github.com/susannaruecker",
        googleScholarLink: "https://scholar.google.com/citations?user=bhvw9esAAAAJ&hl=de",
        emailAddress: "susanna.ruecker@hu-berlin.de",
        linkedInLink: "https://www.linkedin.com/in/susanna-rücker-14801821a/",
    },  {
        name: "Olia Toporkov",
        title: "Guest Researcher",
        category: "Research Scientists",
        image: "/people/olia.jpg",
        gitHubLink: "https://github.com/oltoporkov",
        googleScholarLink: "https://scholar.google.com/citations?user=u6DxJ8YAAAAJ&hl=en&oi=ao",
        emailAddress: "oliatoporkov@gmail.com",
        linkedInLink: "https://www.linkedin.com/in/olia-toporkov-b48744b2/",
    }, {
        name: "Piet Wagner",
        title: "PhD Student",
        image: "/people/piet.jpg",
        category: "Research Scientists",
        linkedInLink: "https://de.linkedin.com/in/piet-wagner/",
        gitHubLink: "https://github.com/PietW",
    }, {
        name: "Franziska Weeber",
        title: "Guest Researcher",
        image: "/people/franzi.jpg",
        category: "Research Scientists",
        emailAddress: "franziska.weeber@hu-berlin.de",
        linkedInLink: "https://www.linkedin.com/in/franziska-weeber/",
        googleScholarLink: "https://scholar.google.com/citations?user=l4TYvw0AAAAJ&hl=de",
    }, {
        name: "Adrian Breiding",
        title: "Research Assistant",
        category: "Student Researchers",
        gitHubLink: "https://github.com/addie9800",
    }, {
        name: "Conrad Dobberstein",
        title: "Research Assistant",
        category: "Student Researchers",
        gitHubLink: "https://github.com/dobbersc",
    }, {
        name: "Lukas Garbas",
        title: "Research Assistant",
        category: "Student Researchers",
        image: "/people/lukas.png",
        gitHubLink: "https://github.com/lukasgarbas",
    }, {
        name: "Teresa Löffelhardt",
        title: "Research Assistant",
        category: "Student Researchers",
        gitHubLink: "https://github.com/teresaloeffelhardt",
        emailAddress: "teresa.loeffelhardt@gmail.com",
    }, {
        name: "Konstantin Lukas",
        title: "Fullstack Developer",
        category: "Student Researchers",
        gitHubLink: "https://github.com/konstantin-lukas",
        emailAddress: "kontakt@konstantinlukas.de",
        websiteLink: "https://konstantinlukas.de",
    }, {
        name: "Sebastian Pohl",
        title: "Research Assistant",
        category: "Student Researchers",
        image: "/people/sebastian.jpg",
        gitHubLink: "https://github.com/oneSebastian",
        emailAddress: "sebastian.pohl@hu-berlin.de",
        linkedInLink: "https://www.linkedin.com/in/sebastian-pohl-902584198/",
        googleScholarLink: "https://scholar.google.com/citations?user=7gohUaEAAAAJ",
    }, {
        name: "Christoph Alt",
        title: "PostDoc",
        category: "Alumni",
        gitHubLink: "https://github.com/ChristophAlt",
    }, {
        name: "Pieter Delobelle",
        title: "PostDoc",
        category: "Alumni",
        websiteLink: "https://pieter.ai/",
    }, {
        name: "Aaron Wey",
        title: "Research Assistant",
        category: "Alumni",
        gitHubLink: "https://github.com/Weyaaron",
    }, {
        name: "Marcel Millich",
        title: "Research Engineer",
        category: "Alumni",
        gitHubLink: "https://github.com/marcelmmm",
    },  {
        name: "Jacek Wiland",
        title: "Research Engineer",
        category: "Alumni",
        image: "/people/jacek.jpg",
        gitHubLink: "https://github.com/stw2",
    },
];